### ISSUE TITLE
CSV support not working

### ISSUE THREAD

**Issue by Vitiell0** [stestagg/pytubes#18]
I installed the latest version with `pip install pytubes` and when I attempt to run the example in the docs `list(Each(['a,b', 'c,d']).csv())` I get `AttributeError: 'tubes.Each' object has no attribute 'csv'`

<img width="946" alt="Screen Shot 2019-03-23 at 10 38 07 AM" src="https://user-images.githubusercontent.com/6282321/54868431-6fd2eb80-4d5a-11e9-88d1-d134ebbe6ba8.png">

Looking at Pypi it looks like 0.6.0 was published in March 2018 and in April 2018 there are some commits made related to CSV support. https://github.com/stestagg/pytubes/pull/17

So I imagine it's related to that. @stestagg could you publish a new version to Pypi?

I also cloned the master and tried using `python setup.py install` and got the error `pyx/ctubes.pyx:275:15: undeclared name not builtin: ReadFileObj`

After removing `read_fileobj` since it looks like its not used anywhere and running setup.py again I got another error: `ar: no archive members specified`

**Comment by stestagg** [comment]
Hi

So sorry about this. I think you’re right.

I’m preparing a new release and will push it in the next few days.

Steve

**Comment by stestagg** [comment]
This was resolved a while ago, I'm closing now, please re-open or create a new issue if you have other issues :)
