### ISSUE TITLE
how to skip blank line when reading json file

### ISSUE THREAD

**Issue by qzshucsz** [stestagg/pytubes#20]
pytubes is a great package which support flexible data iterator, thank you @stestagg . I had read the doc of pytubes, you already implement skip_unless and equals function for us, why not offering skip function which is similar to skip_unless function? There is a skip function which will skip specific rows. I want to use skip_unless and no equal function to skip blank line,  it is an expression such as "skip_unless(lambda x: x.slot(1).no_equal('null')))".
However, i can not implement such effect base on interfaces provided by pytubes. I will be very appriciated if any one can give me some help.

**Comment by stestagg** [comment]
Hi

Thanks for your comments.  I've added a few functions which I think solve what you were asking for.

As you pointed out, skip_unless on its own seems silly.  I've added a 'skip_if' tube, which is the opposite of skip_unless.

I've also added a len() tube which returns the string length of each input.

This is used in the helper function is_blank().  So for your case, assuming you have a file `file.txt` with blank lines, you can do this:

    tubes.Each(['file.txt']).read_files().split().skip_if(tubes.is_blank)

which returns only non-blank lines.

The change has been merged into master, but not released to pypi yet.  Also the documentation builder is not working (readthedocs is running out of memory with the compiling, so it might be a bit before a release)

**Comment by qzshucsz** [comment]
Thank you @stestagg  very much for your quickly and detailed reply.

**Comment by qzshucsz** [comment]
The new methods skip_if() and tubes.is_blank() solve this issue very well. For obtaing iterator of  json files,  skip_if() should be placed between split() and json(), such as "Each(self.__file_list)
                      .read_files()
                      .split()
                      .skip_if(lambda x: x.is_blank())
                      .json()"
