### ISSUE TITLE
https://docs.pytubes.com/ is BAD, where is doc? thanks!

### ISSUE THREAD

**Issue by freelogic** [stestagg/pytubes#26]
https://docs.pytubes.com/ is BAD, where is doc? thanks!

**Comment by pytubes** [comment]
Apologies for this, the readthedocs builder can't cope with the extra overheads of building some recent pyarrow changes.

I'm working on moving the docs to using github actions, but this is a reasonably complex operation

**Comment by stestagg** [comment]
Docs are now back up, thanks for the report!
